### ISSUE TITLE
Slow inference

### ISSUE THREAD

**Issue by 09Kanika** [iiakshat/BriefComm#2]
# Description
The current BriefComm summarizer efficiently converts audio content into text and provides summaries using the Whisper and Llama2 models. However, it has been observed that the summarization process is slower than expected, impacting user experience. Additionally, the Llama2 model has now become outdated with the release of Llama3, which offers improved performance and capabilities.

## Proposed Enhancements

**1. Speed Optimization with Groq Inference:**

- Implement Groq inference to enhance the processing speed of the summarizer.
- As Whisper is already included in Groq inference, integrating it will be straightforward and will significantly improve the transcription speed.

**2. Upgrade to Llama3:**

- Replace the current Llama2 model with the newly released Llama3 model.
- Llama3 offers better performance, accuracy, and efficiency in summarization tasks, providing users with more precise and quicker summaries.

## Feature Integration and Testing:

- Integrate Groq inference into the current workflow to optimize Whisper's transcription process.
- Transition from Llama2 to Llama3 for summarization, ensuring compatibility and seamless operation.
- Conduct extensive testing with diverse datasets to validate the improvements in speed and summarization quality.

 ## Resources:

- Documentation and implementation guides for Groq inference and Whisper.
- Llama3 model and its integration documentation.
- Datasets for testing transcription and summarization improvements.

 ## Assignees:

- Assign this issue to team members experienced with AI model integration, specifically those familiar with Whisper, Groq inference, and the Llama series models.

## Milestone:

- Set a milestone for the completion of these enhancements within the next development cycle to ensure timely updates and improved user experience.

## Labels:

- Enhancement
- Performance
- Speed Optimization

## Additional Information:

- Ensure all contributions follow the GitHub Community Guidelines and maintain high code quality and documentation standards.
- Regularly update the progress on this issue and involve the community for feedback and suggestions.

**Comment by iiakshat** [comment]
Thanks I'll do it. Closing this issue for now.
